import { createHash } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
import { db } from "@/db";
import { chatterItems, mailMessages, userSettings } from "@/db/schema";
import { CONTENT_IS_DATA_DIRECTIVE } from "@/lib/ai/content-directive";
import {
    MAIL_PARTICIPANT_DIRECTIVE,
    MAIL_SUMMARY_PROMPT,
    MAIL_SUMMARY_SYSTEM,
    MAIL_TASKS_DIRECTIVE,
} from "@/lib/ai/mail-summary-prompts";
import { resolveTemplate } from "@/lib/ai/prompt-templates";
import {
    getAiOutputLanguageDirective,
    normalizeSummaryPromptConfig,
    resolveAiOutputLanguage,
    SUMMARY_MARKDOWN_DIRECTIVE,
    SUMMARY_TEMPLATE_KIND,
} from "@/lib/ai/summary-presets";
import { readItemContent } from "@/lib/content/read-item-content";
import { renderMailForModel } from "@/lib/content/render-mail";
import { decryptJsonField, decryptText } from "@/lib/encryption/fields";
import { AppError, ErrorCode } from "@/lib/errors";
import { exportRecordingSidecarsIfEnabled } from "@/lib/export/document-sidecars";
import { maskedContentForModel, secretAddressMasker } from "@/lib/mail/redact";
import { captureServerEvent } from "@/lib/posthog-server";
import { notifyIfShared } from "@/lib/sharing/notify";
import type { ContentRunContext } from "@/lib/sharing/run-context";
import {
    contentWriterRefusalNow,
    writerRefusalError,
} from "@/lib/sharing/writer";
import { taskViewerById } from "@/lib/tasks/access";
import { SUMMARY_TASKS_MERGE_DIRECTIVE } from "@/lib/tasks/directive";
import {
    loadTasksPromptContext,
    resolveTaskProposals,
} from "@/lib/tasks/proposals";
import { upsertEnhancement } from "@/lib/transcription/persist";
import type {
    GenerateSummaryOptions,
    GenerateSummaryResult,
} from "./generate-summary";
import { runSummary, summaryModelFor } from "./summary-model";

/** The built-in mail template's id, reported when no template was chosen. */
export const MAIL_SUMMARY_PROMPT_ID = "mail";

function mailNotSummarized(message: string): AppError {
    return new AppError(ErrorCode.INVALID_INPUT, message, 400);
}

/**
 * Generate (or regenerate) the summary of a mail and its task proposals,
 * stored like a recording's. Mail sent by machines, and mail whose content
 * could not be read, is never summarized. The subject stays the title.
 */
export async function generateMailSummary(
    ctx: ContentRunContext,
    itemId: string,
    opts: GenerateSummaryOptions,
): Promise<GenerateSummaryResult> {
    const orgView = ctx.view === "org";
    const refusal = await contentWriterRefusalNow({
        recordingId: itemId,
        ownerUserId: ctx.ownerUserId,
        actorUserId: ctx.actorUserId,
    });
    if (refusal) throw writerRefusalError(refusal);

    const [mail] = await db
        .select({
            id: chatterItems.id,
            userId: chatterItems.userId,
            title: chatterItems.title,
            occurredAt: chatterItems.occurredAt,
            sentAt: mailMessages.sentAt,
            autoGenerated: mailMessages.autoGenerated,
            unreadable: mailMessages.unreadable,
        })
        .from(chatterItems)
        .innerJoin(
            mailMessages,
            and(
                eq(mailMessages.id, chatterItems.id),
                eq(mailMessages.userId, chatterItems.userId),
            ),
        )
        .where(
            and(
                eq(chatterItems.id, itemId),
                eq(chatterItems.userId, ctx.ownerUserId),
                isNull(chatterItems.deletedAt),
            ),
        )
        .limit(1);
    if (!mail) {
        throw new AppError(
            ErrorCode.RECORDING_NOT_FOUND,
            "Mail not found",
            404,
        );
    }
    if (mail.autoGenerated) {
        throw mailNotSummarized("Mail sent by machines is not summarized.");
    }
    if (mail.unreadable) {
        throw mailNotSummarized("This mail's content is not readable.");
    }
    const stored = await readItemContent(ctx.ownerUserId, itemId);
    if (!stored || stored.segments.length === 0) {
        throw mailNotSummarized("This mail has no text to summarize.");
    }
    const content = await maskedContentForModel(stored);
    const sentAt = mail.sentAt ?? mail.occurredAt;

    const tasksContext = await loadTasksPromptContext({
        recording: {
            id: mail.id,
            userId: mail.userId,
            occurredAt: sentAt,
            timezone: null,
            zonemins: null,
        },
        transcriptionId: null,
        orgView,
        reviewer: await taskViewerById(
            orgView ? ctx.settingsUserId : ctx.ownerUserId,
        ),
        noun: "mail",
    }).catch((error: unknown) => {
        console.error("[summary] task context unavailable:", error);
        return { text: "", refs: new Map<string, string>() };
    });

    const [userSettingsRow] = await db
        .select()
        .from(userSettings)
        .where(eq(userSettings.userId, ctx.settingsUserId))
        .limit(1);
    const [actorSettingsRow] =
        ctx.actorUserId === ctx.settingsUserId
            ? [userSettingsRow]
            : await db
                  .select()
                  .from(userSettings)
                  .where(eq(userSettings.userId, ctx.actorUserId))
                  .limit(1);

    // A chosen template is honoured; otherwise mail gets its own, since the
    // user's default is written for recordings.
    let usedPromptId = MAIL_SUMMARY_PROMPT_ID;
    let promptTemplate = MAIL_SUMMARY_PROMPT;
    if (opts.presetId && opts.presetId !== MAIL_SUMMARY_PROMPT_ID) {
        const promptConfig = normalizeSummaryPromptConfig(
            userSettingsRow?.summaryPrompt
                ? decryptJsonField(userSettingsRow.summaryPrompt)
                : null,
        );
        const resolved = resolveTemplate(
            promptConfig,
            opts.presetId,
            SUMMARY_TEMPLATE_KIND,
        );
        usedPromptId = resolved.id;
        promptTemplate = resolved.prompt;
    }

    const summaryModel = await summaryModelFor(ctx.actorUserId);
    const { credentials, model } = summaryModel;

    const title = decryptText(mail.title);
    const subject = (await secretAddressMasker([title]))(title);
    const mailText = renderMailForModel(content, { subject, sentAt });
    const outputLanguage = resolveAiOutputLanguage(
        userSettingsRow?.aiOutputLanguage,
        content.language ?? userSettingsRow?.defaultTranscriptionLanguage,
    );
    const languageDirective = getAiOutputLanguageDirective(outputLanguage);
    const mergeLanguageDirective = getAiOutputLanguageDirective(
        outputLanguage,
        "extractions",
    );
    // The tasks already decided name what people typed, an address too.
    const tasksText = (await secretAddressMasker([tasksContext.text]))(
        tasksContext.text,
    );
    const prompt = [
        promptTemplate.replaceAll("{transcription}", () => mailText),
        tasksText,
    ]
        .filter(Boolean)
        .join("\n\n");
    const systemContent = [
        MAIL_SUMMARY_SYSTEM,
        CONTENT_IS_DATA_DIRECTIVE,
        SUMMARY_MARKDOWN_DIRECTIVE,
        MAIL_PARTICIPANT_DIRECTIVE,
        MAIL_TASKS_DIRECTIVE,
        languageDirective,
    ]
        .filter(Boolean)
        .join(" ");

    const multiPassOn =
        actorSettingsRow?.summaryMultiPass === true &&
        (opts.trigger !== "auto" || actorSettingsRow?.summaryMultiPassAuto);
    const { payload, multiPass } = await runSummary({
        model: summaryModel,
        usage: {
            itemId,
            ownerUserId: ctx.ownerUserId,
            payerUserId: ctx.actorUserId,
        },
        systemContent,
        prompt,
        mergeSystem: (mergePrompt) =>
            [
                mergePrompt,
                CONTENT_IS_DATA_DIRECTIVE,
                SUMMARY_MARKDOWN_DIRECTIVE,
                MAIL_PARTICIPANT_DIRECTIVE,
                SUMMARY_TASKS_MERGE_DIRECTIVE,
                mergeLanguageDirective,
            ]
                .filter(Boolean)
                .join("\n\n"),
        multiPass: multiPassOn
            ? {
                  rounds: actorSettingsRow?.summaryMultiPassRounds ?? null,
                  mergePrompt: userSettingsRow?.summaryMergePrompt
                      ? decryptText(userSettingsRow.summaryMergePrompt)
                      : null,
              }
            : null,
        onProgress: opts.onProgress,
    });

    const { summary, keyPoints, actionItems } = payload;
    const tasks = await resolveTaskProposals({
        source: "riffado",
        items: payload.taskItems,
        updates: payload.taskUpdates,
        refs: tasksContext.refs,
        ownerUserId: ctx.ownerUserId,
        transcriptionId: null,
        turns: null,
        language: content.language,
        orgView,
        summaryText: summary,
        mail: content,
    }).catch((error: unknown) => {
        console.error("[summary] task proposals unavailable:", error);
        return undefined;
    });

    const { committed, reason } = await upsertEnhancement({
        userId: ctx.contentUserId,
        recordingId: itemId,
        kind: "mail",
        transcriptionId: null,
        summary,
        keyPoints,
        actionItems,
        source: "riffado",
        provider: credentials.provider,
        model,
        multiPass,
        inputFingerprint: createHash("sha256").update(mailText).digest("hex"),
        allowReaped: (opts.trigger ?? "manual") === "manual",
        actorUserId: ctx.actorUserId,
        jobId: opts.jobId,
        tasks,
    });
    if (!committed) {
        if (reason === "cancelled") {
            throw new AppError(
                ErrorCode.NOT_FOUND,
                "The run was cancelled before it finished",
                410,
            );
        }
        if (reason) throw writerRefusalError(reason);
        throw new AppError(ErrorCode.NOT_FOUND, "Mail was deleted", 410);
    }

    await exportRecordingSidecarsIfEnabled(
        ctx.contentUserId,
        itemId,
        "summary",
        "riffado",
    );
    await notifyIfShared(itemId);
    await captureServerEvent({
        distinctId: ctx.actorUserId,
        event: "summary_generated",
        properties: {
            trigger: opts.trigger ?? "manual",
            provider: credentials.provider,
            kind: "mail",
            multi_pass: multiPass !== undefined,
            multi_pass_rounds: multiPass?.roundsRequested,
            multi_pass_passes_used: multiPass?.passesUsed,
            multi_pass_merged: multiPass?.merged,
        },
    });

    return {
        ownerUserId: ctx.ownerUserId,
        summary,
        keyPoints,
        actionItems,
        provider: credentials.provider,
        model,
        promptId: usedPromptId,
        promptFallback:
            opts.presetId !== undefined &&
            opts.presetId !== MAIL_SUMMARY_PROMPT_ID &&
            usedPromptId !== opts.presetId,
        multiPass,
    };
}
