import { and, asc, eq, inArray, isNull } from "drizzle-orm";
import { db } from "@/db";
import {
    aiEnhancements,
    chatterItems,
    mailContents,
    mailMessages,
    mailParticipants,
} from "@/db/schema";
import { decryptJsonField, decryptText } from "@/lib/encryption/fields";
import type { ArchiveScope } from "@/lib/export/archive-scope";
import type { MailAuth } from "@/lib/mail/dkim";
import type { AttachmentMeta } from "@/lib/mail/parse";
import { sharedItemCondition } from "@/lib/sharing/shared";

/** A mail as an archive carries it, beside its raw message. */
export interface ArchivedMail {
    id: string;
    ownerUserId: string;
    subject: string;
    occurredAt: string;
    sentAt: string | null;
    receivedAt: string;
    sizeBytes: number;
    senderVerified: boolean;
    autoGenerated: boolean;
    unreadable: boolean;
    auth: MailAuth | null;
    attachments: AttachmentMeta[];
    participants: {
        ref: string;
        roles: string[];
        name: string | null;
        address: string | null;
        authenticated: boolean;
    }[];
    segments: unknown[];
    /** Its summaries, one per source. */
    summaries: {
        source: string;
        summary: string | null;
        keyPoints: unknown;
        actionItems: unknown;
        provider: string;
        model: string;
        createdAt: string;
    }[];
    /** Where its raw message is stored, encrypted; null once reaped. */
    rawStoragePath: string | null;
}

/**
 * The mail an archive of `scope` carries: a person's own (whether shared
 * or not), or the Organization's (what was shared into its folders).
 * Decrypted, like everything else in an archive.
 */
export async function collectArchivedMail(
    scope: ArchiveScope,
): Promise<ArchivedMail[]> {
    const rows = await db
        .select({
            id: chatterItems.id,
            userId: chatterItems.userId,
            title: chatterItems.title,
            occurredAt: chatterItems.occurredAt,
            sentAt: mailMessages.sentAt,
            receivedAt: mailMessages.receivedAt,
            sizeBytes: mailMessages.sizeBytes,
            senderVerified: mailMessages.senderVerified,
            autoGenerated: mailMessages.autoGenerated,
            unreadable: mailMessages.unreadable,
            auth: mailMessages.auth,
            attachments: mailMessages.attachments,
            rawStoragePath: mailMessages.rawStoragePath,
        })
        .from(chatterItems)
        .innerJoin(
            mailMessages,
            and(
                eq(mailMessages.id, chatterItems.id),
                eq(mailMessages.userId, chatterItems.userId),
            ),
        )
        .where(
            and(
                eq(chatterItems.kind, "mail"),
                isNull(chatterItems.deletedAt),
                scope.kind === "personal"
                    ? eq(chatterItems.userId, scope.userId)
                    : sharedItemCondition(scope.orgUserId),
            ),
        )
        .orderBy(asc(chatterItems.occurredAt), asc(chatterItems.id));
    if (rows.length === 0) return [];
    const ids = rows.map((row) => row.id);
    const [participants, contents, summaries] = await Promise.all([
        db
            .select()
            .from(mailParticipants)
            .where(inArray(mailParticipants.itemId, ids))
            .orderBy(asc(mailParticipants.position)),
        db
            .select({
                itemId: mailContents.itemId,
                segments: mailContents.segments,
            })
            .from(mailContents)
            .where(inArray(mailContents.itemId, ids)),
        db
            .select({
                itemId: aiEnhancements.itemId,
                source: aiEnhancements.source,
                summary: aiEnhancements.summary,
                keyPoints: aiEnhancements.keyPoints,
                actionItems: aiEnhancements.actionItems,
                provider: aiEnhancements.provider,
                model: aiEnhancements.model,
                createdAt: aiEnhancements.createdAt,
            })
            .from(aiEnhancements)
            .innerJoin(
                chatterItems,
                and(
                    eq(chatterItems.id, aiEnhancements.itemId),
                    eq(chatterItems.userId, aiEnhancements.userId),
                ),
            )
            .where(inArray(aiEnhancements.itemId, ids)),
    ]);
    const segmentsOf = new Map(
        contents.map((content) => [
            content.itemId,
            decryptJsonField<unknown[]>(content.segments) ?? [],
        ]),
    );
    return rows.map((row) => ({
        id: row.id,
        ownerUserId: row.userId,
        subject: decryptText(row.title),
        occurredAt: row.occurredAt.toISOString(),
        sentAt: row.sentAt?.toISOString() ?? null,
        receivedAt: row.receivedAt.toISOString(),
        sizeBytes: row.sizeBytes,
        senderVerified: row.senderVerified,
        autoGenerated: row.autoGenerated,
        unreadable: row.unreadable,
        auth: decryptJsonField<MailAuth>(row.auth),
        attachments: decryptJsonField<AttachmentMeta[]>(row.attachments) ?? [],
        participants: participants
            .filter((participant) => participant.itemId === row.id)
            .map((participant) => ({
                ref: participant.ref,
                roles: participant.roles,
                name: participant.name ? decryptText(participant.name) : null,
                address: participant.address
                    ? decryptText(participant.address)
                    : null,
                authenticated: participant.authenticated,
            })),
        segments: segmentsOf.get(row.id) ?? [],
        summaries: summaries
            .filter((summary) => summary.itemId === row.id)
            .map((summary) => ({
                source: summary.source,
                summary: summary.summary ? decryptText(summary.summary) : null,
                keyPoints: decryptJsonField(summary.keyPoints) ?? [],
                actionItems: decryptJsonField(summary.actionItems) ?? [],
                provider: summary.provider,
                model: summary.model,
                createdAt: summary.createdAt.toISOString(),
            })),
        rawStoragePath: row.rawStoragePath,
    }));
}
