import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { apiCredentials, mailMessages, userSettings } from "@/db/schema";
import { pickEnhancementCredential } from "@/lib/ai/enhancement-provider";
import { queueAutoSummary } from "@/lib/summary/auto-summary";

/**
 * Queue the summary of a mail that just arrived, when its owner processes
 * mail automatically (the default) and has a provider that summarizes.
 * Machine-sent and unreadable mail is kept, never processed. Never throws:
 * the mail is stored whatever happens here.
 */
export async function processNewMail(
    ownerUserId: string,
    itemId: string,
): Promise<void> {
    try {
        const [[settings], [mail], credentials] = await Promise.all([
            db
                .select({ mailAutoProcess: userSettings.mailAutoProcess })
                .from(userSettings)
                .where(eq(userSettings.userId, ownerUserId))
                .limit(1),
            db
                .select({
                    autoGenerated: mailMessages.autoGenerated,
                    unreadable: mailMessages.unreadable,
                })
                .from(mailMessages)
                .where(
                    and(
                        eq(mailMessages.id, itemId),
                        eq(mailMessages.userId, ownerUserId),
                    ),
                )
                .limit(1),
            db
                .select()
                .from(apiCredentials)
                .where(eq(apiCredentials.userId, ownerUserId)),
        ]);
        if (settings?.mailAutoProcess === false) return;
        if (!mail || mail.autoGenerated || mail.unreadable) return;
        if (!pickEnhancementCredential(credentials)) return;
        await queueAutoSummary(ownerUserId, itemId, null);
    } catch (error) {
        console.error(
            `[mail] could not queue the processing of mail ${itemId}:`,
            error instanceof Error ? error.message : error,
        );
    }
}
