import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { apiCredentials, mailMessages, userSettings } from "@/db/schema";
import { pickEnhancementCredential } from "@/lib/ai/enhancement-provider";
import { ALL_ITEM_KINDS } from "@/lib/content/item-kinds";
import { env } from "@/lib/env";
import { isLearnAvailableFor } from "@/lib/knowledge/availability";
import { startLearnRun } from "@/lib/learn/learn-job";
import { consumeRateLimitBucket } from "@/lib/rate-limit";
import { resolveRecordingAccess } from "@/lib/sharing/access";
import { queueAutoSummary } from "@/lib/summary/auto-summary";

/**
 * Process a mail that just arrived, when its owner processes mail
 * automatically (the default) and has a provider that summarizes: queue
 * its summary, and with automatic Learn on, start Learn too. The summary
 * does not wait for Learn's review, as a recording's does: Learn changes
 * no word of a mail. Machine-sent and unreadable mail is kept, never
 * processed. Never throws: the mail is stored whatever happens here.
 */
export async function processNewMail(
    ownerUserId: string,
    itemId: string,
): Promise<void> {
    try {
        const [[settings], [mail], credentials] = await Promise.all([
            db
                .select({
                    mailAutoProcess: userSettings.mailAutoProcess,
                    autoLearn: userSettings.autoLearn,
                })
                .from(userSettings)
                .where(eq(userSettings.userId, ownerUserId))
                .limit(1),
            db
                .select({
                    autoGenerated: mailMessages.autoGenerated,
                    unreadable: mailMessages.unreadable,
                })
                .from(mailMessages)
                .where(
                    and(
                        eq(mailMessages.id, itemId),
                        eq(mailMessages.userId, ownerUserId),
                    ),
                )
                .limit(1),
            db
                .select()
                .from(apiCredentials)
                .where(eq(apiCredentials.userId, ownerUserId)),
        ]);
        if (settings?.mailAutoProcess === false) return;
        if (!mail || mail.autoGenerated || mail.unreadable) return;
        if (!pickEnhancementCredential(credentials)) return;
        await queueAutoSummary(ownerUserId, itemId, null);
        if (settings?.autoLearn) await autoLearnMail(ownerUserId, itemId);
    } catch (error) {
        console.error(
            `[mail] could not queue the processing of mail ${itemId}:`,
            error instanceof Error ? error.message : error,
        );
    }
}

/** Automatic Learn on a new mail, under automatic Learn's hourly cap. */
async function autoLearnMail(
    ownerUserId: string,
    itemId: string,
): Promise<void> {
    if (!(await isLearnAvailableFor(ownerUserId))) return;
    const access = await resolveRecordingAccess(ownerUserId, itemId, {
        kinds: ALL_ITEM_KINDS,
    });
    // Shared already (a retry merged into a shared item): the
    // Organization's curator runs Learn there.
    if (!access || access.role !== "owner" || access.shared) return;
    const rateLimit = await consumeRateLimitBucket(
        `auto-learn:user:${ownerUserId}`,
        {
            limit: env.AUTO_SUMMARY_RATE_LIMIT_PER_HOUR,
            windowMs: 60 * 60 * 1000,
        },
    );
    if (!rateLimit.allowed) return;
    await startLearnRun({
        access: { ...access, view: "private", contentUserId: ownerUserId },
        actorUserId: ownerUserId,
        source: "riffado",
        trigger: "auto",
    });
}
