import { and, asc, eq, inArray } from "drizzle-orm";
import { db } from "@/db";
import {
    chatterItems,
    mailContents,
    mailMessages,
    mailParticipants,
    mailPendingShares,
    recordingFolderAssignments,
    recordingFolders,
    users,
} from "@/db/schema";
import type { ContentSegment } from "@/lib/content/types";
import { decryptJsonField, decryptText } from "@/lib/encryption/fields";
import { type MailAccess, resolveMailAccess } from "@/lib/mail/access";
import type { MailAuth } from "@/lib/mail/dkim";
import type { AttachmentMeta } from "@/lib/mail/parse";
import { secretAddressMasker } from "@/lib/mail/redact";
import { getOrgUserId } from "@/lib/org/config";

export interface MailParticipantView {
    ref: string;
    roles: string[];
    name: string | null;
    address: string | null;
    authenticated: boolean;
}

/**
 * A mail as its detail page shows it: to its owner, or read-only to anyone
 * while it is shared into the Organization.
 */
export interface MailDetail {
    id: string;
    /** The viewer owns it; otherwise it is read through the Organization. */
    isOwn: boolean;
    /** Display name of the owner, for whoever else reads it. */
    ownerName: string | null;
    subject: string;
    occurredAt: string;
    sentAt: string | null;
    receivedAt: string;
    sizeBytes: number;
    senderVerified: boolean;
    autoGenerated: boolean;
    unreadable: boolean;
    hasRaw: boolean;
    /** When retention removed the message as it arrived, its text, its summary. */
    rawReapedAt: string | null;
    contentReapedAt: string | null;
    summaryReapedAt: string | null;
    participants: MailParticipantView[];
    segments: (Omit<ContentSegment, "at"> & { at: string | null })[];
    attachments: AttachmentMeta[];
    auth: MailAuth | null;
    /** Organization folders it waits to be shared into (D2); owner only. */
    pendingShares: { folderId: string; name: string }[];
    /** The folders it is filed into the viewer can see. */
    folderIds: string[];
}

/** The live mail `itemId` as `viewerUserId` may read it, decrypted, or null. */
export async function loadMailDetail(
    viewerUserId: string,
    itemId: string,
): Promise<MailDetail | null> {
    const access = await resolveMailAccess(viewerUserId, itemId);
    if (!access) return null;
    const ownerUserId = access.ownerUserId;
    const isOwn = access.role === "owner";
    const [row] = await db
        .select({
            id: chatterItems.id,
            title: chatterItems.title,
            occurredAt: chatterItems.occurredAt,
            sentAt: mailMessages.sentAt,
            receivedAt: mailMessages.receivedAt,
            sizeBytes: mailMessages.sizeBytes,
            senderVerified: mailMessages.senderVerified,
            autoGenerated: mailMessages.autoGenerated,
            unreadable: mailMessages.unreadable,
            rawStoragePath: mailMessages.rawStoragePath,
            rawReapedAt: mailMessages.rawReapedAt,
            contentReapedAt: chatterItems.contentReapedAt,
            summaryReapedAt: chatterItems.summaryReapedAt,
            attachments: mailMessages.attachments,
            auth: mailMessages.auth,
            ownerName: users.name,
            ownerEmail: users.email,
        })
        .from(chatterItems)
        .innerJoin(users, eq(users.id, chatterItems.userId))
        .innerJoin(
            mailMessages,
            and(
                eq(mailMessages.id, chatterItems.id),
                eq(mailMessages.userId, chatterItems.userId),
            ),
        )
        .where(
            and(
                eq(chatterItems.id, itemId),
                eq(chatterItems.userId, ownerUserId),
                eq(chatterItems.kind, "mail"),
            ),
        )
        .limit(1);
    if (!row) return null;
    const orgUserId = isOwn ? null : await getOrgUserId();
    const [participants, [content], pending, assignments] = await Promise.all([
        db
            .select()
            .from(mailParticipants)
            .where(
                and(
                    eq(mailParticipants.itemId, itemId),
                    eq(mailParticipants.userId, ownerUserId),
                ),
            )
            .orderBy(asc(mailParticipants.position)),
        db
            .select({ segments: mailContents.segments })
            .from(mailContents)
            .where(
                and(
                    eq(mailContents.itemId, itemId),
                    eq(mailContents.userId, ownerUserId),
                ),
            )
            .limit(1),
        isOwn
            ? db
                  .select({ folderId: mailPendingShares.folderId })
                  .from(mailPendingShares)
                  .where(
                      and(
                          eq(mailPendingShares.itemId, itemId),
                          eq(mailPendingShares.userId, ownerUserId),
                      ),
                  )
            : Promise.resolve([]),
        db
            .select({ folderId: recordingFolderAssignments.folderId })
            .from(recordingFolderAssignments)
            .innerJoin(
                recordingFolders,
                eq(recordingFolders.id, recordingFolderAssignments.folderId),
            )
            .where(
                and(
                    eq(recordingFolderAssignments.itemId, itemId),
                    eq(recordingFolderAssignments.userId, ownerUserId),
                    // The owner's private folders are theirs alone.
                    orgUserId
                        ? eq(recordingFolders.userId, orgUserId)
                        : undefined,
                ),
            ),
    ]);
    const pendingFolders =
        pending.length > 0
            ? await db
                  .select({
                      id: recordingFolders.id,
                      name: recordingFolders.name,
                  })
                  .from(recordingFolders)
                  .where(
                      inArray(
                          recordingFolders.id,
                          pending.map((share) => share.folderId),
                      ),
                  )
            : [];
    const segments =
        decryptJsonField<
            (Omit<ContentSegment, "at"> & { at: string | null })[]
        >(content?.segments) ?? [];
    const people = participants.map((participant) => ({
        ref: participant.ref,
        roles: participant.roles,
        name: participant.name ? decryptText(participant.name) : null,
        address: participant.address ? decryptText(participant.address) : null,
        authenticated: participant.authenticated,
    }));
    const subject = decryptText(row.title);
    const attachments =
        decryptJsonField<AttachmentMeta[]>(row.attachments) ?? [];
    const mask = isOwn
        ? (text: string) => text
        : await secretAddressMasker([
              subject,
              ...people.flatMap((person) => [
                  person.name ?? "",
                  person.address ?? "",
              ]),
              ...segments.map((segment) => segment.text),
              ...attachments.map((attachment) => attachment.filename ?? ""),
          ]);
    return {
        id: row.id,
        isOwn,
        ownerName: isOwn ? null : row.ownerName || row.ownerEmail,
        subject: mask(subject),
        occurredAt: row.occurredAt.toISOString(),
        sentAt: row.sentAt?.toISOString() ?? null,
        receivedAt: row.receivedAt.toISOString(),
        sizeBytes: row.sizeBytes,
        senderVerified: row.senderVerified,
        autoGenerated: row.autoGenerated,
        unreadable: row.unreadable,
        // The message as it arrived carries every header unmasked.
        hasRaw: isOwn && row.rawStoragePath !== null,
        rawReapedAt: row.rawReapedAt?.toISOString() ?? null,
        contentReapedAt: row.contentReapedAt?.toISOString() ?? null,
        summaryReapedAt: row.summaryReapedAt?.toISOString() ?? null,
        participants: people.map((person) => ({
            ...person,
            name: person.name ? mask(person.name) : null,
            address: person.address ? mask(person.address) : null,
        })),
        segments: segments.map((segment) => ({
            ...segment,
            text: mask(segment.text),
            at: segment.at ? new Date(segment.at).toISOString() : null,
        })),
        attachments: attachments.map((attachment) => ({
            ...attachment,
            filename: attachment.filename ? mask(attachment.filename) : null,
        })),
        auth: decryptJsonField<MailAuth>(row.auth),
        pendingShares: pendingFolders.map((folder) => ({
            folderId: folder.id,
            name: decryptText(folder.name),
        })),
        folderIds: assignments.map((assignment) => assignment.folderId),
    };
}

/**
 * Where the raw message of the mail `itemId` is stored, and whose it is, as
 * `viewerUserId` may read it; null when they may not or it is gone.
 */
export async function mailRawFor(
    viewerUserId: string,
    itemId: string,
): Promise<{ access: MailAccess; path: string } | null> {
    const access = await resolveMailAccess(viewerUserId, itemId);
    if (!access) return null;
    const [row] = await db
        .select({ path: mailMessages.rawStoragePath })
        .from(mailMessages)
        .where(
            and(
                eq(mailMessages.id, itemId),
                eq(mailMessages.userId, access.ownerUserId),
            ),
        )
        .limit(1);
    return row?.path ? { access, path: row.path } : null;
}
