import { and, asc, eq, inArray } from "drizzle-orm";
import { db } from "@/db";
import {
    chatterItems,
    mailContents,
    mailMessages,
    mailParticipants,
    mailPendingShares,
    recordingFolderAssignments,
    recordingFolders,
} from "@/db/schema";
import type { ContentSegment } from "@/lib/content/types";
import { decryptJsonField, decryptText } from "@/lib/encryption/fields";
import type { MailAuth } from "@/lib/mail/dkim";
import type { AttachmentMeta } from "@/lib/mail/parse";

export interface MailParticipantView {
    ref: string;
    roles: string[];
    name: string | null;
    address: string | null;
    authenticated: boolean;
}

/** A mail as its detail page shows it. Owner only. */
export interface MailDetail {
    id: string;
    subject: string;
    occurredAt: string;
    sentAt: string | null;
    receivedAt: string;
    sizeBytes: number;
    senderVerified: boolean;
    autoGenerated: boolean;
    unreadable: boolean;
    hasRaw: boolean;
    participants: MailParticipantView[];
    segments: (Omit<ContentSegment, "at"> & { at: string | null })[];
    attachments: AttachmentMeta[];
    auth: MailAuth | null;
    /** Organization folders it waits to be shared into (D2). */
    pendingShares: { folderId: string; name: string }[];
    /** The owner's folders it is filed into. */
    folderIds: string[];
}

/** The owner's live mail `itemId`, decrypted, or null. */
export async function loadMailDetail(
    ownerUserId: string,
    itemId: string,
): Promise<MailDetail | null> {
    const [row] = await db
        .select({
            id: chatterItems.id,
            title: chatterItems.title,
            occurredAt: chatterItems.occurredAt,
            sentAt: mailMessages.sentAt,
            receivedAt: mailMessages.receivedAt,
            sizeBytes: mailMessages.sizeBytes,
            senderVerified: mailMessages.senderVerified,
            autoGenerated: mailMessages.autoGenerated,
            unreadable: mailMessages.unreadable,
            rawStoragePath: mailMessages.rawStoragePath,
            attachments: mailMessages.attachments,
            auth: mailMessages.auth,
        })
        .from(chatterItems)
        .innerJoin(
            mailMessages,
            and(
                eq(mailMessages.id, chatterItems.id),
                eq(mailMessages.userId, chatterItems.userId),
            ),
        )
        .where(
            and(
                eq(chatterItems.id, itemId),
                eq(chatterItems.userId, ownerUserId),
                eq(chatterItems.kind, "mail"),
            ),
        )
        .limit(1);
    if (!row) return null;
    const [participants, [content], pending, assignments] = await Promise.all([
        db
            .select()
            .from(mailParticipants)
            .where(
                and(
                    eq(mailParticipants.itemId, itemId),
                    eq(mailParticipants.userId, ownerUserId),
                ),
            )
            .orderBy(asc(mailParticipants.position)),
        db
            .select({ segments: mailContents.segments })
            .from(mailContents)
            .where(
                and(
                    eq(mailContents.itemId, itemId),
                    eq(mailContents.userId, ownerUserId),
                ),
            )
            .limit(1),
        db
            .select({ folderId: mailPendingShares.folderId })
            .from(mailPendingShares)
            .where(
                and(
                    eq(mailPendingShares.itemId, itemId),
                    eq(mailPendingShares.userId, ownerUserId),
                ),
            ),
        db
            .select({ folderId: recordingFolderAssignments.folderId })
            .from(recordingFolderAssignments)
            .where(
                and(
                    eq(recordingFolderAssignments.itemId, itemId),
                    eq(recordingFolderAssignments.userId, ownerUserId),
                ),
            ),
    ]);
    const pendingFolders =
        pending.length > 0
            ? await db
                  .select({
                      id: recordingFolders.id,
                      name: recordingFolders.name,
                  })
                  .from(recordingFolders)
                  .where(
                      inArray(
                          recordingFolders.id,
                          pending.map((share) => share.folderId),
                      ),
                  )
            : [];
    const segments =
        decryptJsonField<
            (Omit<ContentSegment, "at"> & { at: string | null })[]
        >(content?.segments) ?? [];
    return {
        id: row.id,
        subject: decryptText(row.title),
        occurredAt: row.occurredAt.toISOString(),
        sentAt: row.sentAt?.toISOString() ?? null,
        receivedAt: row.receivedAt.toISOString(),
        sizeBytes: row.sizeBytes,
        senderVerified: row.senderVerified,
        autoGenerated: row.autoGenerated,
        unreadable: row.unreadable,
        hasRaw: row.rawStoragePath !== null,
        participants: participants.map((participant) => ({
            ref: participant.ref,
            roles: participant.roles,
            name: participant.name ? decryptText(participant.name) : null,
            address: participant.address
                ? decryptText(participant.address)
                : null,
            authenticated: participant.authenticated,
        })),
        segments: segments.map((segment) => ({
            ...segment,
            at: segment.at ? new Date(segment.at).toISOString() : null,
        })),
        attachments: decryptJsonField<AttachmentMeta[]>(row.attachments) ?? [],
        auth: decryptJsonField<MailAuth>(row.auth),
        pendingShares: pendingFolders.map((folder) => ({
            folderId: folder.id,
            name: decryptText(folder.name),
        })),
        folderIds: assignments.map((assignment) => assignment.folderId),
    };
}

/** Where the owner's live mail's raw message is stored, or null. */
export async function mailRawPath(
    ownerUserId: string,
    itemId: string,
): Promise<string | null> {
    const [row] = await db
        .select({ path: mailMessages.rawStoragePath })
        .from(mailMessages)
        .innerJoin(
            chatterItems,
            and(
                eq(chatterItems.id, mailMessages.id),
                eq(chatterItems.userId, mailMessages.userId),
            ),
        )
        .where(
            and(
                eq(mailMessages.id, itemId),
                eq(mailMessages.userId, ownerUserId),
            ),
        )
        .limit(1);
    return row?.path ?? null;
}
