import { and, desc, eq, inArray, isNull, sql } from "drizzle-orm";
import { db } from "@/db";
import {
    chatterItems,
    mailMessages,
    mailParticipants,
    mailPendingShares,
} from "@/db/schema";
import { decryptText } from "@/lib/encryption/fields";
import type { Recording } from "@/types/recording";

/**
 * The owner's live mail as rows of the Chatter pile, newest first: the
 * subject as the row's title, the sender beside it. Decrypted here, on the
 * server.
 */
export async function loadMailListRows(
    ownerUserId: string,
): Promise<Recording[]> {
    const rows = await db
        .select({
            id: chatterItems.id,
            title: chatterItems.title,
            occurredAt: chatterItems.occurredAt,
            sizeBytes: mailMessages.sizeBytes,
            senderVerified: mailMessages.senderVerified,
            autoGenerated: mailMessages.autoGenerated,
            hasAttachments: sql<boolean>`${mailMessages.attachments} is not null`,
        })
        .from(chatterItems)
        .innerJoin(
            mailMessages,
            and(
                eq(mailMessages.id, chatterItems.id),
                eq(mailMessages.userId, chatterItems.userId),
            ),
        )
        .where(
            and(
                eq(chatterItems.userId, ownerUserId),
                eq(chatterItems.kind, "mail"),
                isNull(chatterItems.deletedAt),
            ),
        )
        .orderBy(desc(chatterItems.occurredAt), desc(chatterItems.id));
    if (rows.length === 0) return [];
    const ids = rows.map((row) => row.id);
    const [senders, waiting] = await Promise.all([
        db
            .select({
                itemId: mailParticipants.itemId,
                name: mailParticipants.name,
                address: mailParticipants.address,
            })
            .from(mailParticipants)
            .where(
                and(
                    eq(mailParticipants.userId, ownerUserId),
                    inArray(mailParticipants.itemId, ids),
                    sql`${mailParticipants.roles} @> '["from"]'::jsonb`,
                ),
            ),
        db
            .select({ itemId: mailPendingShares.itemId })
            .from(mailPendingShares)
            .where(
                and(
                    eq(mailPendingShares.userId, ownerUserId),
                    inArray(mailPendingShares.itemId, ids),
                ),
            ),
    ]);
    const fromOf = new Map(
        senders.map((sender) => [
            sender.itemId,
            sender.name
                ? decryptText(sender.name)
                : sender.address
                  ? decryptText(sender.address)
                  : null,
        ]),
    );
    const waitingIds = new Set(waiting.map((row) => row.itemId));
    return rows.map((row) => ({
        id: row.id,
        kind: "mail" as const,
        filename: decryptText(row.title),
        duration: 0,
        startTime: row.occurredAt.toISOString(),
        filesize: row.sizeBytes,
        deviceSn: "mail",
        hasTranscript: false,
        hasSummary: false,
        audioReaped: false,
        waveformPeaks: null,
        mail: {
            from: fromOf.get(row.id) ?? null,
            senderVerified: row.senderVerified,
            hasAttachments: row.hasAttachments,
            waitingToShare: waitingIds.has(row.id),
            autoGenerated: row.autoGenerated,
        },
    }));
}
