import { and, desc, eq, inArray, isNull, type SQL, sql } from "drizzle-orm";
import { db } from "@/db";
import {
    chatterItems,
    mailMessages,
    mailParticipants,
    mailPendingShares,
    users,
} from "@/db/schema";
import { decryptText } from "@/lib/encryption/fields";
import { secretAddressMasker } from "@/lib/mail/redact";
import { sharedItemCondition } from "@/lib/sharing/shared";
import type { Recording } from "@/types/recording";

async function mailRows(
    where: SQL | undefined,
    view: { viewerUserId: string; organization: boolean },
): Promise<Recording[]> {
    const rows = await db
        .select({
            id: chatterItems.id,
            userId: chatterItems.userId,
            title: chatterItems.title,
            occurredAt: chatterItems.occurredAt,
            sizeBytes: mailMessages.sizeBytes,
            senderVerified: mailMessages.senderVerified,
            autoGenerated: mailMessages.autoGenerated,
            hasAttachments: sql<boolean>`${mailMessages.attachments} is not null`,
            ownerName: users.name,
            ownerEmail: users.email,
        })
        .from(chatterItems)
        .innerJoin(
            mailMessages,
            and(
                eq(mailMessages.id, chatterItems.id),
                eq(mailMessages.userId, chatterItems.userId),
            ),
        )
        .innerJoin(users, eq(users.id, chatterItems.userId))
        .where(
            and(
                eq(chatterItems.kind, "mail"),
                isNull(chatterItems.deletedAt),
                where,
            ),
        )
        .orderBy(desc(chatterItems.occurredAt), desc(chatterItems.id));
    if (rows.length === 0) return [];
    const ids = rows.map((row) => row.id);
    const [senders, waiting] = await Promise.all([
        db
            .select({
                itemId: mailParticipants.itemId,
                name: mailParticipants.name,
                address: mailParticipants.address,
            })
            .from(mailParticipants)
            .innerJoin(
                chatterItems,
                and(
                    eq(chatterItems.id, mailParticipants.itemId),
                    eq(chatterItems.userId, mailParticipants.userId),
                ),
            )
            .where(
                and(
                    inArray(mailParticipants.itemId, ids),
                    sql`${mailParticipants.roles} @> '["from"]'::jsonb`,
                ),
            ),
        view.organization
            ? Promise.resolve([])
            : db
                  .select({ itemId: mailPendingShares.itemId })
                  .from(mailPendingShares)
                  .where(
                      and(
                          eq(mailPendingShares.userId, view.viewerUserId),
                          inArray(mailPendingShares.itemId, ids),
                      ),
                  ),
    ]);
    const fromOf = new Map(
        senders.map((sender) => [
            sender.itemId,
            sender.name
                ? decryptText(sender.name)
                : sender.address
                  ? decryptText(sender.address)
                  : null,
        ]),
    );
    const waitingIds = new Set(waiting.map((row) => row.itemId));
    const subjects = new Map(
        rows.map((row) => [row.id, decryptText(row.title)]),
    );
    // Only the owner sees their secret addresses whole.
    const mask = view.organization
        ? await secretAddressMasker([
              ...subjects.values(),
              ...[...fromOf.values()].map((from) => from ?? ""),
          ])
        : (text: string) => text;
    return rows.map((row) => {
        const from = fromOf.get(row.id);
        return {
            id: row.id,
            kind: "mail" as const,
            filename: mask(subjects.get(row.id) ?? ""),
            duration: 0,
            startTime: row.occurredAt.toISOString(),
            filesize: row.sizeBytes,
            deviceSn: "mail",
            hasTranscript: false,
            hasSummary: false,
            audioReaped: false,
            waveformPeaks: null,
            mail: {
                from: from ? mask(from) : null,
                senderVerified: row.senderVerified,
                hasAttachments: row.hasAttachments,
                waitingToShare: waitingIds.has(row.id),
                autoGenerated: row.autoGenerated,
            },
            ...(view.organization
                ? {
                      view: "org" as const,
                      isOwn: row.userId === view.viewerUserId,
                      ownerName: row.ownerName || row.ownerEmail,
                  }
                : {}),
        };
    });
}

/**
 * The owner's live mail as rows of the Chatter pile, newest first: the
 * subject as the row's title, the sender beside it. Decrypted here, on the
 * server.
 */
export async function loadMailListRows(
    ownerUserId: string,
): Promise<Recording[]> {
    return mailRows(eq(chatterItems.userId, ownerUserId), {
        viewerUserId: ownerUserId,
        organization: false,
    });
}

/**
 * Every mail shared into the Organization, as rows of its library: read
 * by every account, with its owner named.
 */
export async function loadSharedMailRows(
    viewerUserId: string,
    orgUserId: string,
): Promise<Recording[]> {
    return mailRows(sharedItemCondition(orgUserId), {
        viewerUserId,
        organization: true,
    });
}
