import {
    type AddressObject,
    type Attachment,
    type ParsedMail,
    simpleParser,
} from "mailparser";
import type { ParsedMailbox } from "@/lib/mail/address-list";

/** An attachment as stored and listed: never its content. */
export interface AttachmentMeta {
    /** Its position among the message's attachments, for download. */
    index: number;
    filename: string | null;
    contentType: string;
    size: number;
    contentId: string | null;
    inline: boolean;
}

/** A message as the app reads it. */
export interface ParsedMessage {
    subject: string;
    sentAt: Date | null;
    messageId: string | null;
    inReplyTo: string | null;
    references: string[];
    from: ParsedMailbox[];
    sender: ParsedMailbox | null;
    to: ParsedMailbox[];
    cc: ParsedMailbox[];
    replyTo: ParsedMailbox[];
    text: string | null;
    html: string | null;
    attachments: AttachmentMeta[];
    /** Machine-sent: auto-replies, lists, delivery reports, invitations. */
    autoGenerated: boolean;
    /** Nothing readable: encrypted (S/MIME, PGP) or only a TNEF blob. */
    unreadable: boolean;
}

/** HTML longer than this is not parsed into text (mailparser's own cap). */
const MAX_HTML_LENGTH = 2 * 1024 * 1024;

function mailboxes(
    value: AddressObject | AddressObject[] | undefined,
): ParsedMailbox[] {
    const objects = value ? (Array.isArray(value) ? value : [value]) : [];
    const out: ParsedMailbox[] = [];
    const visit = (entries: AddressObject["value"]) => {
        for (const entry of entries) {
            if (entry.group) visit(entry.group);
            else if (entry.address) {
                out.push({
                    address: entry.address.trim().toLowerCase(),
                    name: (entry.name ?? "").trim(),
                });
            }
        }
    };
    for (const object of objects) visit(object.value);
    return out;
}

function headerText(mail: ParsedMail, name: string): string {
    const value = mail.headers.get(name);
    if (value === undefined || value === null) return "";
    if (typeof value === "string") return value;
    if (typeof value === "object" && "value" in value) {
        return String((value as { value: unknown }).value ?? "");
    }
    return String(value);
}

const AUTO_FROM = /^(mailer-daemon|postmaster|forwarding-noreply)@/i;

function isAutoGenerated(
    mail: ParsedMail,
    from: readonly ParsedMailbox[],
): boolean {
    const autoSubmitted = headerText(mail, "auto-submitted").toLowerCase();
    if (autoSubmitted && autoSubmitted !== "no") return true;
    if (mail.headers.has("list-id")) return true;
    const precedence = headerText(mail, "precedence").toLowerCase();
    if (["bulk", "list", "junk", "auto_reply"].includes(precedence))
        return true;
    if (mail.headers.has("x-autoreply") || mail.headers.has("x-autorespond")) {
        return true;
    }
    const contentType = headerText(mail, "content-type").toLowerCase();
    if (contentType.startsWith("multipart/report")) return true;
    if (from.some((mailbox) => AUTO_FROM.test(mailbox.address))) return true;
    return mail.attachments.some(
        (attachment) =>
            attachment.contentType.toLowerCase() === "text/calendar",
    );
}

function isUnreadable(mail: ParsedMail, text: string | null): boolean {
    const contentType = headerText(mail, "content-type").toLowerCase();
    if (
        contentType.startsWith("multipart/encrypted") ||
        contentType.startsWith("application/pkcs7-mime") ||
        contentType.startsWith("application/x-pkcs7-mime")
    ) {
        return true;
    }
    if (text?.trimStart().startsWith("-----BEGIN PGP MESSAGE-----")) {
        return true;
    }
    const readable = Boolean(text?.trim()) || Boolean(mail.html);
    if (readable) return false;
    return mail.attachments.some((attachment: Attachment) =>
        [
            "application/ms-tnef",
            "application/vnd.ms-tnef",
            "application/pkcs7-mime",
            "application/x-pkcs7-mime",
        ].includes(attachment.contentType.toLowerCase()),
    );
}

function messageIds(value: string[] | string | undefined): string[] {
    if (!value) return [];
    return (Array.isArray(value) ? value : value.split(/\s+/))
        .map((id) => id.trim())
        .filter(Boolean);
}

/** Parses a raw message. Attachments are listed, never kept. */
export async function parseMessage(raw: Buffer): Promise<ParsedMessage> {
    const mail = await simpleParser(raw, {
        skipHtmlToText: true,
        skipTextToHtml: true,
        skipImageLinks: true,
        keepCidLinks: true,
        maxHtmlLengthToParse: MAX_HTML_LENGTH,
    });
    const from = mailboxes(mail.from);
    const [sender] = mailboxes(
        mail.headers.get("sender") as AddressObject | undefined,
    );
    const text = mail.text?.trim() ? mail.text : null;
    return {
        subject: (mail.subject ?? "").trim(),
        sentAt:
            mail.date && !Number.isNaN(mail.date.getTime()) ? mail.date : null,
        messageId: mail.messageId?.trim() || null,
        inReplyTo: mail.inReplyTo?.trim() || null,
        references: messageIds(mail.references),
        from,
        sender:
            sender &&
            !from.some((mailbox) => mailbox.address === sender.address)
                ? sender
                : null,
        to: mailboxes(mail.to),
        cc: mailboxes(mail.cc),
        replyTo: mailboxes(mail.replyTo),
        text,
        html: mail.html || null,
        attachments: mail.attachments.map((attachment, index) => ({
            index,
            filename: attachment.filename ?? null,
            contentType: attachment.contentType,
            size: attachment.size,
            contentId: attachment.contentId ?? attachment.cid ?? null,
            inline: attachment.contentDisposition === "inline",
        })),
        autoGenerated: isAutoGenerated(mail, from),
        unreadable: isUnreadable(mail, text),
    };
}

/**
 * The attachment at `index` of a raw message, content included, for a
 * download; null when there is none.
 */
export async function readAttachment(
    raw: Buffer,
    index: number,
): Promise<{ meta: AttachmentMeta; content: Buffer } | null> {
    const mail = await simpleParser(raw, {
        skipHtmlToText: true,
        skipTextToHtml: true,
        skipImageLinks: true,
        keepCidLinks: true,
    });
    const attachment = mail.attachments[index];
    if (!attachment) return null;
    return {
        meta: {
            index,
            filename: attachment.filename ?? null,
            contentType: attachment.contentType,
            size: attachment.size,
            contentId: attachment.contentId ?? attachment.cid ?? null,
            inline: attachment.contentDisposition === "inline",
        },
        content: attachment.content,
    };
}
