"use client";

import { GraduationCap, Loader2 } from "lucide-react";
import { useExtracted } from "next-intl";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getApiErrorMessage } from "@/lib/api-errors";
import type {
    MailFactPayload,
    MailNewRecordPayload,
    MailTextAnchor,
} from "@/lib/learn/mail-candidates";
import type { ReviewItemView, ReviewView } from "@/lib/learn/review";
import type { MailDetail } from "@/lib/mail/detail";
import { cn } from "@/lib/utils";
import type { Recording } from "@/types/recording";

const POLL_MS = 3_000;

type Side =
    | { personId: string }
    | { entityId: string }
    | { newRef: string }
    | { speakerLabel: string }
    | { literal: string };

/**
 * What Learn found in a mail, to tick and apply: new people and things
 * (participants among them, with their address), and the facts the mail
 * states, each with the words it was found in. A quoted part's facts, and
 * those of a sender nothing verified, start unticked.
 */
export function MailLearnCard({
    mail,
    detail,
    canChange,
}: {
    mail: Recording;
    detail: MailDetail;
    canChange: boolean;
}) {
    const i18n = useExtracted();
    const query = mail.view === "org" ? "?view=org" : "";
    const base = `/api/recordings/${encodeURIComponent(mail.id)}`;
    const [review, setReview] = useState<ReviewView | null>(null);
    const [busy, setBusy] = useState(false);

    const load = useCallback(async () => {
        const response = await fetch(`${base}/review${query}`).catch(
            () => null,
        );
        if (response?.ok) setReview((await response.json()) as ReviewView);
    }, [base, query]);

    useEffect(() => {
        setReview(null);
        void load();
    }, [load]);

    const status = review?.run?.status;
    const learning = status === "queued" || status === "running";
    useEffect(() => {
        if (!learning) return;
        const timer = setInterval(() => void load(), POLL_MS);
        return () => clearInterval(timer);
    }, [learning, load]);

    if (!canChange || mail.mail?.autoGenerated || detail.unreadable) {
        return null;
    }

    const start = async () => {
        setBusy(true);
        try {
            const response = await fetch(`${base}/learn${query}`, {
                method: "POST",
            });
            if (!response.ok) {
                toast.error(
                    await getApiErrorMessage(
                        response,
                        i18n("Learn could not start."),
                    ),
                );
                return;
            }
            await load();
        } finally {
            setBusy(false);
        }
    };

    const decide = async (item: ReviewItemView, accepted: boolean) => {
        // "The same person as …?": yes is that person.
        const maybe =
            item.kind === "new_record"
                ? (item.payload as unknown as MailNewRecordPayload).maybe
                : undefined;
        const response = await fetch(
            `${base}/review/items/${encodeURIComponent(item.id)}${query}`,
            {
                method: "PATCH",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    decision: accepted ? "accepted" : "rejected",
                    version: item.version,
                    ...(accepted && maybe ? { choice: maybe } : {}),
                }),
            },
        );
        if (!response.ok) {
            toast.error(i18n("The review changed; reload it."));
            await load();
            return;
        }
        const { version } = (await response.json()) as { version: number };
        setReview((current) =>
            current
                ? {
                      ...current,
                      items: current.items.map((candidate) =>
                          candidate.id === item.id
                              ? {
                                    ...candidate,
                                    version,
                                    decision: accepted
                                        ? "accepted"
                                        : "rejected",
                                }
                              : candidate,
                      ),
                  }
                : current,
        );
    };

    const finish = async () => {
        if (!review) return;
        setBusy(true);
        try {
            const response = await fetch(`${base}/review/finish${query}`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    versions: Object.fromEntries(
                        review.items.map((item) => [item.id, item.version]),
                    ),
                }),
            });
            if (!response.ok) {
                toast.error(
                    await getApiErrorMessage(
                        response,
                        i18n("The review could not be finished."),
                    ),
                );
                return;
            }
            const finished = (await response.json()) as { applied: number };
            toast.success(
                i18n(
                    "{count, plural, one {# change made} other {# changes made}}",
                    { count: finished.applied },
                ),
            );
            await load();
        } finally {
            setBusy(false);
        }
    };

    const words = (anchor: MailTextAnchor | undefined) => {
        if (!anchor) return null;
        const segment = detail.segments.find(
            (candidate) => candidate.index === anchor.segmentIndex,
        );
        return segment?.text.slice(anchor.charStart, anchor.charEnd).trim();
    };
    const recordOf = (ref: string) =>
        review?.items.find(
            (item) =>
                item.kind === "new_record" &&
                (item.payload as unknown as MailNewRecordPayload).ref === ref,
        );
    const nameOf = (side: Side): string => {
        if ("literal" in side) return `“${side.literal}”`;
        if ("personId" in side) return review?.names[side.personId] ?? "?";
        if ("entityId" in side) return review?.names[side.entityId] ?? "?";
        if ("newRef" in side) {
            const record = recordOf(side.newRef);
            return record
                ? (record.payload as unknown as MailNewRecordPayload).name
                : "?";
        }
        const participant = detail.participants.find(
            (candidate) => candidate.ref === side.speakerLabel,
        );
        return participant?.name ?? participant?.address ?? side.speakerLabel;
    };
    const ticked = (item: ReviewItemView) =>
        (item.decision ?? (item.preTicked ? "accepted" : "rejected")) ===
        "accepted";

    const items = (review?.items ?? []).filter(
        (item) => item.kind !== "relation_phrase",
    );
    const ready = status === "ready";

    return (
        <Card>
            <CardContent className="space-y-3 p-4 sm:p-6">
                <div className="flex items-center justify-between gap-3">
                    <h3 className="flex items-center gap-1.5 text-sm font-medium">
                        <GraduationCap className="size-4" />
                        {i18n("Learn")}
                    </h3>
                    {!learning && !ready && (
                        <Button
                            size="sm"
                            variant="outline"
                            disabled={busy}
                            onClick={() => void start()}
                        >
                            {busy && (
                                <Loader2 className="size-4 animate-spin" />
                            )}
                            {i18n("Learn from this mail")}
                        </Button>
                    )}
                </div>
                {learning && (
                    <p className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Loader2 className="size-4 animate-spin" />
                        {i18n("Reading the mail…")}
                    </p>
                )}
                {status === "finished" && review?.items.length === 0 && (
                    <p className="text-sm text-muted-foreground">
                        {i18n("Learn found nothing new in this mail.")}
                    </p>
                )}
                {status === "failed" && (
                    <p className="text-sm text-destructive">
                        {i18n("Learn could not read this mail.")}
                    </p>
                )}
                {(ready || status === "finished") && items.length > 0 && (
                    <ul className="space-y-2">
                        {items.map((item) => {
                            const record =
                                item.kind === "new_record"
                                    ? (item.payload as unknown as MailNewRecordPayload)
                                    : null;
                            const fact =
                                item.kind === "new_record"
                                    ? null
                                    : (item.payload as unknown as MailFactPayload);
                            const quote = record
                                ? words(record.evidence[0])
                                : words(fact?.text);
                            return (
                                <li
                                    key={item.id}
                                    className={cn(
                                        "flex items-start gap-2 rounded-md border p-2 text-sm",
                                        !ready && "opacity-80",
                                    )}
                                >
                                    {ready && (
                                        <input
                                            type="checkbox"
                                            className="mt-1"
                                            checked={ticked(item)}
                                            aria-label={i18n("Apply this")}
                                            onChange={(event) =>
                                                void decide(
                                                    item,
                                                    event.target.checked,
                                                )
                                            }
                                        />
                                    )}
                                    <div className="min-w-0 space-y-1">
                                        {record?.maybe ? (
                                            <p>
                                                {i18n(
                                                    "{name}: the same person as {known}?",
                                                    {
                                                        name: record.name,
                                                        known: nameOf(
                                                            record.maybe as Side,
                                                        ),
                                                    },
                                                )}
                                                {record.address && (
                                                    <span className="text-muted-foreground">
                                                        {" "}
                                                        · {record.address}
                                                    </span>
                                                )}
                                            </p>
                                        ) : record ? (
                                            <p>
                                                {record.kind === "person"
                                                    ? i18n(
                                                          "New person: {name}",
                                                          {
                                                              name: record.name,
                                                          },
                                                      )
                                                    : i18n(
                                                          "New thing: {name}",
                                                          {
                                                              name: record.name,
                                                          },
                                                      )}
                                                {record.address && (
                                                    <span className="text-muted-foreground">
                                                        {" "}
                                                        · {record.address}
                                                    </span>
                                                )}
                                            </p>
                                        ) : fact ? (
                                            <p>
                                                {nameOf(fact.subject as Side)}{" "}
                                                <span className="text-muted-foreground">
                                                    {review?.relations[
                                                        fact.relationKey
                                                    ] ?? fact.relationKey}
                                                </span>{" "}
                                                {nameOf(fact.object as Side)}
                                            </p>
                                        ) : null}
                                        {quote && (
                                            <p className="text-xs italic text-muted-foreground">
                                                “{quote}”
                                            </p>
                                        )}
                                        {fact?.provenance && (
                                            <p className="text-xs text-amber-700 dark:text-amber-400">
                                                {fact.provenance === "quoted"
                                                    ? i18n(
                                                          "Quoted from an earlier message: what its author wrote, not the sender",
                                                      )
                                                    : i18n(
                                                          "From a sender nothing verified",
                                                      )}
                                            </p>
                                        )}
                                        {!ready && item.outcome && (
                                            <p className="text-xs text-muted-foreground">
                                                {item.outcome === "applied"
                                                    ? i18n("Applied")
                                                    : item.outcome ===
                                                        "rejected"
                                                      ? i18n("Left out")
                                                      : i18n("Not applied")}
                                            </p>
                                        )}
                                    </div>
                                </li>
                            );
                        })}
                    </ul>
                )}
                {ready && (
                    <div className="flex justify-end">
                        <Button
                            size="sm"
                            disabled={busy}
                            onClick={() => void finish()}
                        >
                            {busy && (
                                <Loader2 className="size-4 animate-spin" />
                            )}
                            {i18n("Apply what is ticked")}
                        </Button>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
