"use client";

import { ListChecks, Loader2, Sparkles } from "lucide-react";
import { useExtracted } from "next-intl";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { Markdown } from "@/components/markdown";
import { RecordingTasks } from "@/components/tasks/recording-tasks";
import { TaskReviewLink } from "@/components/tasks/task-review-dialog";
import { useRecordingTasks } from "@/components/tasks/use-recording-tasks";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getApiErrorMessage } from "@/lib/api-errors";
import type { Recording } from "@/types/recording";

interface StoredSummary {
    summary: string | null;
    keyPoints?: string[];
    actionItems?: string[];
}

const NO_SPEAKERS: never[] = [];

/**
 * A mail's summary, key points and tasks, and the button that makes them.
 * Machine-sent mail has none and offers none.
 */
export function MailSummaryCard({
    mail,
    canChange,
}: {
    mail: Recording;
    /** The viewer may make the summary: the owner, or the organization account on a shared mail. */
    canChange: boolean;
}) {
    const i18n = useExtracted();
    const view = mail.view === "org" ? "org" : "private";
    const query = view === "org" ? "?view=org" : "";
    const [summary, setSummary] = useState<StoredSummary | null>(null);
    const [loaded, setLoaded] = useState(false);
    const [running, setRunning] = useState(false);
    const [reloadKey, setReloadKey] = useState(0);
    const taskState = useRecordingTasks(mail.id, reloadKey);

    useEffect(() => {
        const controller = new AbortController();
        setSummary(null);
        setLoaded(false);
        fetch(
            `/api/recordings/${encodeURIComponent(mail.id)}/summary${query}`,
            {
                signal: controller.signal,
            },
        )
            .then(async (response) => {
                if (!response.ok) throw new Error(String(response.status));
                setSummary((await response.json()) as StoredSummary);
            })
            .catch(() => undefined)
            .finally(() => {
                if (!controller.signal.aborted) setLoaded(true);
            });
        return () => controller.abort();
    }, [mail.id, query]);

    const summarize = useCallback(async () => {
        setRunning(true);
        try {
            const response = await fetch(
                `/api/recordings/${encodeURIComponent(mail.id)}/summary${query}`,
                {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: "{}",
                },
            );
            if (!response.ok) {
                toast.error(
                    await getApiErrorMessage(
                        response,
                        i18n("The mail could not be summarized."),
                    ),
                );
                return;
            }
            if (response.status === 202) {
                toast.info(i18n("The summary is still being made."));
                return;
            }
            setSummary((await response.json()) as StoredSummary);
            setReloadKey((key) => key + 1);
        } finally {
            setRunning(false);
        }
    }, [i18n, mail.id, query]);

    if (mail.mail?.autoGenerated) return null;
    const hasSummary = Boolean(summary?.summary);

    return (
        <Card>
            <CardContent className="space-y-4 p-4 sm:p-6">
                <div className="flex items-center justify-between gap-3">
                    <h3 className="flex items-center gap-1.5 text-sm font-medium">
                        <ListChecks className="size-4" />
                        {i18n("Summary")}
                    </h3>
                    {canChange && (
                        <Button
                            size="sm"
                            variant={hasSummary ? "outline" : "default"}
                            disabled={running}
                            onClick={() => void summarize()}
                        >
                            {running ? (
                                <Loader2 className="size-4 animate-spin" />
                            ) : (
                                <Sparkles className="size-4" />
                            )}
                            {hasSummary
                                ? i18n("Summarize again")
                                : i18n("Summarize")}
                        </Button>
                    )}
                </div>
                {!loaded ? (
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Loader2 className="size-4 animate-spin" />
                        {i18n("Loading…")}
                    </div>
                ) : hasSummary ? (
                    <div className="space-y-3">
                        <div className="rounded-lg bg-muted p-4 text-sm">
                            <Markdown>{summary?.summary ?? ""}</Markdown>
                        </div>
                        {(summary?.keyPoints?.length ?? 0) > 0 && (
                            <ul className="space-y-1">
                                {summary?.keyPoints?.map((point) => (
                                    <li
                                        key={`kp-${point.slice(0, 32)}`}
                                        className="flex items-start gap-2 text-sm text-muted-foreground"
                                    >
                                        <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                                        <Markdown inline>{point}</Markdown>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>
                ) : (
                    <p className="text-sm text-muted-foreground">
                        {canChange
                            ? i18n(
                                  'No summary yet. Click "Summarize" to make one and propose its tasks.',
                              )
                            : i18n("No summary yet.")}
                    </p>
                )}
                <TaskReviewLink
                    state={taskState}
                    speakers={NO_SPEAKERS}
                    organizationOnly={view === "org"}
                    allowAdd={hasSummary}
                />
                <RecordingTasks
                    state={taskState}
                    speakers={NO_SPEAKERS}
                    organizationOnly={view === "org"}
                    fallback={null}
                    allowAdd={hasSummary}
                />
            </CardContent>
        </Card>
    );
}
